import { PortfolioItem, SectionType } from "./types";

export const PORTFOLIO_ITEMS: PortfolioItem[] = [
  {
    id: "intro",
    type: SectionType.INTRO,
    title: "Harsh Sinha",
    subtitle: "CS & Data Analytics @ IIT Patna",
    shortDescription:
      "Building at the intersection of Finance, AI, and Engineering.",
    colorTheme: "bg-slate-50",
    description:
      "CS & Data Science undergrad at IIT Patna. Builder at the intersection of AI, finance, and product. Experienced with LLM pipelines, backend systems (TypeScript, Prisma, Postgres), and data-driven UX. Currently exploring GenAI systems, Web3, Quant Finance, creative dev, and high-fidelity interfaces.",
  },
  {
    id: "header-experience",
    type: SectionType.SECTION_HEADER,
    title: "EXPERIENCE",
    subtitle: "",
    colorTheme: "",
    accentClass: "text-blue-500",
    shortDescription: "",
    description: "",
  },
  {
    id: "exp-multibagg",
    type: SectionType.EXPERIENCE,
    title: "Multibagg AI",
    subtitle: "Founder's Office & AI Engineer",
    year: "2025",
    client: "Multibagg AI",
    techStack: ["Python", "Azure", "RAG", "Pinecone", "Next.js", "PostHog"],
    colorTheme: "bg-blue-50",
    shortDescription:
      "Analyzed 60+ IPOs and built automated financial insight pipelines.",
    mbaiImageDescription:
      "Multibagg AI is an AI powered stock research and analysis platform",
    description:
      "Engineered an AI pipeline converting RHP PDFs to Zod schemas via GPT-4o/Gemini using Azure Queues. Reduced manual analysis from hours to minutes. Built an AI Screener Agent translating natural language to SQL, achieving 90% faster response times.",
    stats: [
      { label: "Impressions", value: "13x in 3mo" },
      { label: "Storage Savings", value: "80%" },
    ],
    bullets: [
      "Analyzed 60+ IPOs and 50+ financial results to drive product decisions, feature development, and platform content.",
      "Engineered an AI pipeline converting RHP PDFs to Zod schemas via GPT-4o/Gemini using Azure Queues and Storage; reduced manual analysis from hours to minutes and integrated with a RAG + Pinecone chatbot.",
      "Built an ETF factsheet ingestion system using Document Understanding for LLMs with schema mapping, enabling scalable extraction of PE, PB, holdings, and ratio data with high accuracy.",
      "Developed an FII/DII investment flow analytics module with dynamic querying, enabling one-click 10-year sector, industry, and index-level insights.",
      "Revamped AI chatbot architecture and migrated Redis to a cluster setup, increasing reliability and scalability.",
      "Optimized Pinecone imports (17M+ records), reducing storage and retrieval costs by 80%.",
      "Built an AI Screener Agent translating natural language to optimized SQL; achieved 90% faster response times than peers (e.g., Perplexity) with higher accuracy.",
      "Integrated PostHog, Google Analytics, and UTM tracking; executed Google Ads and SEO initiatives increasing impressions by 13x in 3 months.",
      "Developed multiple quantitative cron jobs and pipelines to extract, analyze, and generate insights from Investor Presentations and Concall PDFs.",
      "Created an AI News Agent for India, US, EU, and global markets; automated ingestion, ranking, and posting to Twitter, driving 200k+ impressions in 10 days.",
      "Built an automated blog generation system using Gemini Doc Understanding and MDX + Next.js, driving a 20x increase in Google Search Console impressions.",
      "Contributed to the development of the agentic chatbot Ask Iris, including a multi-agent architecture with a RAG agent indexing 100k+ Markdown documents, DB and web access, and end-to-end evals.",
    ],
    link: "https://www.multibagg.ai",
    ogImage: "https://www.multibagg.ai/opengraph-image.png",
  },
  {
    id: "header-projects",
    type: SectionType.SECTION_HEADER,
    title: "PROJECTS",
    subtitle: "",
    colorTheme: "",
    accentClass: "text-purple-500",
    shortDescription: "",
    description: "",
  },
  {
    id: "proj-tinycats",
    type: SectionType.PROJECT,
    title: "Tiny Cats",
    subtitle: "Interactive AI Explanations",
    year: "May 2025",
    techStack: ["TypeScript", "Next.js", "Gemini API", "Vercel"],
    colorTheme: "bg-orange-50",
    shortDescription:
      "Explaining complex concepts with adorable feline metaphors.",
    description:
      "Built a Vercel-deployed web app using Gemini API with dual agents that explains complex concepts via interactive cat-themed slides. Implemented a dynamic front-end enabling real-time generation of explanations.",
    link: "https://github.com/harshsinha-12",
  },
  {
    id: "proj-stock",
    type: SectionType.PROJECT,
    title: "Stock Predictor",
    subtitle: "ML Forecasting Engine",
    year: "July 2025",
    techStack: ["Python", "Flask", "Streamlit", "Scikit-learn", "Docker"],
    colorTheme: "bg-green-50",
    shortDescription: "Random Forest system to predict daily stock movements.",
    description:
      "Developed a Random Forest–based system to predict daily stock price movement with custom model training and visualization dashboards. Dockerized for deployment with a dual architecture (Flask backend + Streamlit UI).",
    github: "https://github.com/harshsinha-12",
  },
  {
    id: "proj-candle",
    type: SectionType.PROJECT,
    title: "Candlestick AI",
    subtitle: "Technical Analysis Automation",
    year: "March 2025",
    techStack: ["Python", "Plotly", "yfinance", "Gemini Gen AI"],
    colorTheme: "bg-red-50",
    shortDescription: "AI-driven interpretation of bullish/bearish patterns.",
    description:
      "Created a Streamlit app that fetches live stock data, visualizes candlestick charts, and uses Gemini AI to interpret patterns. Automated end-to-end pipeline enabling instant technical insights.",
    github: "https://github.com/harshsinha-12",
  },
  {
    id: "header-about",
    type: SectionType.SECTION_HEADER,
    title: "ABOUT",
    subtitle: "",
    colorTheme: "",
    accentClass: "text-green-500",
    shortDescription: "",
    description: "",
  },
  {
    id: "about",
    type: SectionType.ABOUT,
    title: "About Me",
    subtitle: "The person behind the code",
    colorTheme: "bg-purple-50",
    shortDescription: "Data Geek. Backend and AI Engineer. Problem Solver.",
    description:
      "I love programming 3D and 2D websites with good design and beautiful animations. National Finalist at India Fintech Forum 2024. 'If my code doesn’t crash once while building it, was it even learning?'",
  },
  {
    id: "contact",
    type: SectionType.CONTACT,
    title: "Get in Touch",
    subtitle: "Let's build something together",
    colorTheme: "bg-slate-100",
    shortDescription: "sinha.harshsep@gmail.com",
    description:
      "Open to Software Engineering, AI/ML, and product-focused development opportunities.",
    link: "mailto:sinha.harshsep@gmail.com",
  },
];
