import { PortfolioItem, SectionType } from "./types";

export const PORTFOLIO_ITEMS: PortfolioItem[] = [
  {
    id: "intro",
    type: SectionType.INTRO,
    title: "Harsh Sinha",
    subtitle: "CS & Data Analytics @ IIT Patna",
    shortDescription:
      "Building at the intersection of Finance, AI, and Engineering.",
    colorTheme: "bg-slate-50",
    description:
      "CS & Data Science undergrad at IIT Patna. Builder at the intersection of AI, finance, and product. Experienced with LLM pipelines, backend systems (TypeScript, Prisma, Postgres), and data-driven UX. Currently exploring GenAI systems, Web3, Quant Finance, creative dev, and high-fidelity interfaces.",
  },
  {
    id: "header-experience",
    type: SectionType.SECTION_HEADER,
    title: "EXPERIENCE",
    subtitle: "",
    colorTheme: "",
    accentClass: "text-blue-500",
    shortDescription: "",
    description: "",
  },
  {
    id: "exp-multibagg",
    type: SectionType.EXPERIENCE,
    title: "Multibagg AI",
    subtitle: "Founder's Office",
    year: "January 2025 — Present",
    client: "Multibagg AI",
    techStack: [
      "TypeScript",
      "Python",
      "Next.js",
      "LLM Agents",
      "RAG",
      "Qdrant",
      "Pinecone",
      "Redis",
      "Postgres",
      "Azure",
    ],
    colorTheme: "bg-blue-50",
    shortDescription:
      "Engineering multi-agent stock research and financial intelligence systems at production scale.",
    mbaiImageDescription:
      "Multibagg AI is an AI powered stock research and analysis platform",
    description:
      "Engineering Ask Iris, Multibagg AI's multi-agent stock research chatbot, alongside production financial data pipelines, retrieval infrastructure, evaluation systems, and real-time market automation covering thousands of companies and millions of records.",
    stats: [
      { label: "User Queries", value: "500K+" },
      { label: "X Impressions", value: "3.2M+" },
      { label: "Documents", value: "100K+" },
      { label: "Financial Records", value: "20M+" },
    ],
    bullets: [
      "Engineered core workflows for Ask Iris, a multi-agent stock research chatbot serving 500K+ user queries, including subagents, tool calling, financial data fetchers, SQL and RAG tools, web search, source citations, and streamed UI components.",
      "Built Qdrant-backed retrieval over 100K+ documents and 20M+ records with hybrid search, reranking, metadata filters, improved chunking, and page-level citations.",
      "Established end-to-end agent evaluation pipelines using LLM-as-a-Judge, custom test sets, tool-call validation, citation checks, latency tracking, response quality scoring, and structured failure analysis.",
      "Engineered IPO and ETF intelligence pipelines using Pydantic and Zod schemas, embeddings, queue workers, OCR, document understanding, and RAG to reduce manual analysis from hours to minutes.",
      "Automated production cron jobs and financial analytics pipelines for 300+ ratios and technical indicators spanning valuation, beta, volatility, oscillators, FII/DII flows, sector rotation, portfolio benchmarks, shareholding, deals, and earnings.",
      "Created an AI Screener Agent that translates natural-language investing queries into optimized SQL and filter logic, supported by schema mapping, evals, logging, and prompt optimization.",
      "Optimized Pinecone and Qdrant infrastructure to improve retrieval quality while reducing vector storage and retrieval costs by up to 80%.",
      "Built real-time AI systems for Union Budget speech, financial news, and exchange announcements covering 6K+ companies with live transcription, relevance, importance, sentiment, and company-level summaries.",
      "Scaled a fully automated Twitter/X intelligence engine to 3.2M+ impressions in 6 months with no human intervention.",
      "Worked on Redis Cluster architecture for scalable caching and fault tolerance, including master-replica failover, VM deployment, key access patterns, and production migration planning.",
    ],
    link: "https://www.multibagg.ai",
    ogImage: "https://www.multibagg.ai/opengraph-image.png",
  },
  {
    id: "header-projects",
    type: SectionType.SECTION_HEADER,
    title: "PROJECTS",
    subtitle: "",
    colorTheme: "",
    accentClass: "text-purple-500",
    shortDescription: "",
    description: "",
  },
  {
    id: "proj-go-rabbit",
    type: SectionType.PROJECT,
    title: "Go Rabbit",
    subtitle: "Agentic AI Contributor Assistant",
    year: "June 2026",
    techStack: ["TypeScript", "Next.js", "OpenAI", "GitHub API", "Zod"],
    colorTheme: "bg-violet-50",
    shortDescription:
      "Agentic contributor assistant that turns approved Go issues into validated PR drafts.",
    description:
      "An agentic AI contributor assistant for approved Go repositories that automates issue selection, repository scanning, patch generation, validation, and pull request drafting through a guarded, user-approved workflow.",
    bullets: [
      "Supports 4 approved Go repositories with server-side allowlisting and issue classification.",
      "Runs a 12-stage guarded workflow with repository scanning, patch generation, git apply --check, validation retries, and explicit user approval before PR creation.",
      "Enforces 120-second validation timeouts and streams terminal logs throughout the workflow.",
      "Generates draft pull requests with a manual compare URL fallback when automated creation is unavailable.",
      "Produces downloadable PDF reports containing the diff, validation results, and agent traces.",
    ],
    link: "https://go-rabbit-sable.vercel.app",
    github: "https://github.com/harshsinha-12/go-rabbit",
    ogImage: "/go-rabbit.png",
  },
  {
    id: "proj-llm-trading-arena",
    type: SectionType.PROJECT,
    title: "LLM Trading Arena (Nifty 50)",
    subtitle: "Research-Grade Paper Trading Arena",
    year: "2026",
    techStack: [
      "Node.js",
      "TypeScript",
      "Redis",
      "BullMQ",
      "Next.js",
      "Postgres",
    ],
    colorTheme: "bg-amber-50",
    shortDescription:
      "Auditable LLM paper trading arena for Nifty 50 with deterministic replay.",
    description:
      "A research-grade, auditable paper trading arena where LLMs compete on Nifty 50, built for realism, reproducibility, and long-term profitability experimentation. The system combines a Node.js and TypeScript engine, Redis-backed append-only logs, BullMQ orchestration, quant feature computation, and a read-only Next.js dashboard.",
    bullets: [
      "Built around a static Nifty 50 universe with daily or controlled hybrid trading to reduce noisy intraday decisions.",
      "Uses rich OHLC-derived quant features, cross-sectional ranks, and regime-aware signals for better model context.",
      "Tracks portfolio-level analytics including HHI concentration, drawdown, MAE, MFE, turnover, and cost drag.",
      "Maintains an append-only Redis storage contract with deterministic replay for full auditability.",
      "Runs idempotent BullMQ cron jobs for OHLC ingestion, feature computation, news workflows, and per-tick simulation.",
      "Supports strict JSON LLM outputs with retry-once validation and no-trade fallback on invalid responses.",
      "Includes a read-only Next.js dashboard for leaderboard, portfolios, trades, and run configuration visibility.",
      "Designed to add Iris as a master agent with broader context and stronger reasoning over the trading loop.",
    ],
    link: "https://the-llm-trading-arena-frontend.vercel.app",
    github: "https://the-llm-trading-arena-frontend.vercel.app",
    ogImage: "/llm-arena.png",
  },
  {
    id: "proj-instagram-creative-intelligence",
    type: SectionType.PROJECT,
    title: "Instagram Creative Intelligence Analyzer",
    subtitle: "AI-Powered Social Creative Analysis",
    year: "June 2026",
    techStack: ["TypeScript", "Next.js", "OpenAI", "Zod", "FFmpeg", "SSE"],
    colorTheme: "bg-pink-50",
    shortDescription:
      "Ranks high-signal Instagram posts and turns reel evidence into strategy reports.",
    description:
      "An AI-powered Instagram intelligence platform that analyzes public brand and competitor accounts, ranks top-performing posts, extracts creative evidence from reels, and generates actionable strategy reports.",
    bullets: [
      "Orchestrates a multi-agent pipeline for data collection, deterministic scoring, media processing, transcription, frame description, creative analysis, pattern aggregation, and recommendations.",
      "Implements Zod-validated inputs, in-memory job orchestration, SSE progress streaming, JSON artifact storage, and structured report rendering.",
      "Scores posts using relative views, engagement rate, velocity per day, comment rate, and like rate before running expensive AI analysis on high-signal content.",
      "Uses FFmpeg and ffprobe to extract audio, sample frames every 5 seconds, and combine captions, metrics, transcripts, and visual evidence into AI insights.",
      "Generates scorecards, top-reel breakdowns, recurring creative patterns, and prioritized action plans.",
    ],
    link: "https://instagram-analysis-red.vercel.app",
    github: "https://github.com/harshsinha-12/instagram-analysis",
    ogImage: "/insta.png",
  },
  {
    id: "proj-tinycats",
    type: SectionType.PROJECT,
    title: "Tiny Cats",
    subtitle: "Interactive AI Explanations",
    year: "May 2025",
    techStack: ["TypeScript", "Next.js", "Gemini API", "Vercel"],
    colorTheme: "bg-orange-50",
    shortDescription:
      "Explaining complex concepts with adorable feline metaphors.",
    description:
      "Built a Vercel-deployed web app using Gemini API with dual agents that explains complex concepts via interactive cat-themed slides. Implemented a dynamic front-end enabling real-time generation of explanations.",
    link: "https://kitty-explains.vercel.app",
    github: "https://github.com/harshsinha-12/kitty-explains",
  },
  {
    id: "proj-stock",
    type: SectionType.PROJECT,
    title: "Stock Predictor",
    subtitle: "ML Forecasting Engine",
    year: "July 2025",
    techStack: ["Python", "Flask", "Streamlit", "Scikit-learn", "Docker"],
    colorTheme: "bg-green-50",
    shortDescription: "Random Forest system to predict daily stock movements.",
    description:
      "Developed a Random Forest–based system to predict daily stock price movement with custom model training and visualization dashboards. Dockerized for deployment with a dual architecture (Flask backend + Streamlit UI).",
    github: "https://github.com/harshsinha-12/stock-predictor-docker",
  },
  {
    id: "proj-candle",
    type: SectionType.PROJECT,
    title: "Candlestick AI",
    subtitle: "Technical Analysis Automation",
    year: "March 2025",
    techStack: ["Python", "Plotly", "yfinance", "Gemini Gen AI"],
    colorTheme: "bg-red-50",
    shortDescription: "AI-driven interpretation of bullish/bearish patterns.",
    description:
      "Created a Streamlit app that fetches live stock data, visualizes candlestick charts, and uses Gemini AI to interpret patterns. Automated end-to-end pipeline enabling instant technical insights.",
    github: "https://github.com/harshsinha-12/Candlestick-analysis",
    ogImage: "/candlestick.png",
  },
  {
    id: "proj-student-perf",
    type: SectionType.PROJECT,
    title: "Student Performance",
    subtitle: "End-to-End ML Project",
    year: "2025",
    techStack: [
      "Python",
      "Flask",
      "Streamlit",
      "Docker",
      "Scikit-learn",
      "AWS/Azure",
    ],
    colorTheme: "bg-emerald-50",
    shortDescription: "Predicting student math scores with ML pipelines.",
    description:
      "An end-to-end machine learning project that predicts student performance based on demographic and educational data. Features a deployment-ready pipeline with Flask api and Streamlit dashboard.",
    bullets: [
      "Flask web application for predictions and a Streamlit interactive dashboard for analysis.",
      "Complete ML pipeline with data preprocessing, feature engineering, and model training.",
      "Containerized with Docker for easy deployment and scalability.",
      "Automated CI/CD workflows using GitHub Actions for building and pushing Docker images.",
      "Deployed on cloud platforms (AWS Elastic Beanstalk / Azure / Google Cloud Run).",
    ],
    link: "https://github.com/harshsinha-12",
    github: "https://github.com/harshsinha-12",
    ogImage: "/student-performance-cover.png",
  },
  {
    id: "proj-scamshield",
    type: SectionType.PROJECT,
    title: "ScamShield",
    subtitle: "AI Security Assistant",
    year: "2025",
    techStack: [
      "Gemini 3 Pro",
      "Multimodal AI",
      "Android",
      "React Native",
      "Node.js",
    ],
    colorTheme: "bg-blue-50",
    shortDescription: "Multimodal AI security assistant to combat fraud.",
    description:
      "ScamShield is a privacy-first, multimodal AI security assistant powered by Gemini 3 Pro. It analyzes screenshots, voice calls, messages, and URLs holistically to detect manipulation patterns and malicious intent.",
    bullets: [
      "Multimodal Reasoning: Analyzes audio, screenshots, and text simultaneously.",
      "Golden Hour Defense: Intervents realtime during fraud attempts.",
      "Grandparent Mode: Simplified UI with read-aloud guidance for seniors.",
      "Frictionless Reporting: Automated complaint generation for authorities.",
      "Privacy-First: Client-side heuristics and redacted analysis.",
    ],
    link: "https://www.kaggle.com/competitions/gemini-3/writeups/new-writeup-1765275812290",
    github:
      "https://www.kaggle.com/competitions/gemini-3/writeups/new-writeup-1765275812290",
    ogImage: "/scamshield-cover.png",
  },
  {
    id: "header-about",
    type: SectionType.SECTION_HEADER,
    title: "ABOUT",
    subtitle: "",
    colorTheme: "",
    accentClass: "text-green-500",
    shortDescription: "",
    description: "",
  },
  {
    id: "about",
    type: SectionType.ABOUT,
    title: "About Me",
    subtitle: "The person behind the code",
    colorTheme: "bg-purple-50",
    shortDescription: "Data Geek. Backend and AI Engineer. Problem Solver.",
    description:
      "I love programming 3D and 2D websites with good design and beautiful animations. National Finalist at India Fintech Forum 2024. 'If my code doesn’t crash once while building it, was it even learning?'",
  },
  {
    id: "contact",
    type: SectionType.CONTACT,
    title: "Get in Touch",
    subtitle: "Let's build something together",
    colorTheme: "bg-slate-100",
    shortDescription: "sinha.harshsep@gmail.com",
    description:
      "Open to Software Engineering, AI/ML, and product-focused development opportunities.",
    link: "mailto:sinha.harshsep@gmail.com",
  },
];
